api:
  tableId-service:
    uri: http://localhost:8091/tableid
  product-service:
    uri: http://localhost:8083/product
  customer-service:
    uri: http://localhost:8087/customer
  movement-account-service:
    uri: http://localhost:8088/movement-account
server:
  port: '8086'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost